### ISSUE TITLE
Notes from JOSS review

### ISSUE THREAD

**Issue by cescalara** [ptiede/Comrade.jl#162]
Hi @ptiede, thanks for your work on Comrade.jl - I enjoyed testing out the examples and the documentation is very thorough. I have a few minor comments that I hope can be useful:

* I think the paper/docs could benefit from a brief explanation of the likelihood used to connect the prior model to the EHT data. How is this done? What assumptions are made? How does uncertainty on the data/model side come into this? Maybe it is a standard procedure in the field, in which case a reference can be added.

* In a general setting, the user should check the diagnostics of whichever tool they use for optimization/posterior sampling. While this is package-dependent and not part of your code, I think adding some extra steps to the tutorial would make sense to encourage such a workflow. E.g. for AHMC in the black hole image tutorial, the effective sample size and rhat are standard diagnostics.

* I ran the black hole image example several times and once ran into the following error when calling 
  ```julia
  plot(sqrt.(meanimg), title="Mean Image")
  ERROR: LoadError: DomainError with -5.97700199247224e-20:
  sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
  ```

* I wanted to check out the performance claims in the docs (Benchmarks) but I didn't manage to get the code running. The code snippet in the docs fails with
  ```julia
  ERROR: LoadError: MethodError: no method matching transform(::TransformVariables.TransformTuple{NamedTuple{(:rad, :wid, :a, :b, :f, :sig, :asy, :pa, :x, :y), NTuple{10, TransformVariables.ScaledShiftedLogistic{Float64}}}}, ::NamedTuple{(:f, :rad, :wid, :a, :b, :sig, :asy, :pa, :x, :y), NTuple{10, Float64}})
  ```
  I also found some recently updated code in `examples/benchmark.jl` in the GitHub, but I didn't manage to get that running       either:
  ```julia
  ERROR: LoadError: ArgumentError: keys(transformations) == keys(y) must hold. Got
  keys(transformations) => (:rad, :wid, :a, :b, :f, :sig, :asy, :pa, :x, :y)
  keys(y) => (:f, :rad, :wid, :a, :b, :sig, :asy, :pa, :x, :y)
  ```

* Does the approach used in [this paper](https://arxiv.org/pdf/2002.05218.pdf) with [this software](https://zenodo.org/record/5499897#.YuVTcC8Rpf0) also merit a mention in the "similar packages" section of the paper?

* I notice that you have automated tests set up but the CI is currently failing and the coverage is currently 0%, although in usually around 75%. Is this a temporary bug with the workflows/uploading?

**Comment by cescalara** [comment]
Linking the review https://github.com/openjournals/joss-reviews/issues/4457

**Comment by ptiede** [comment]
Hi @cescalara thanks for looking into the package! Let me start to go through this item by item!

> I think the paper/docs could benefit from a brief explanation of the likelihood used to connect the prior model to the EHT data. How is this done? What assumptions are made? How does uncertainty on the data/model side come into this? Maybe it is a standard procedure in the field, in which case a reference can be added.

I added a very very brief explanation about the likelihood we use in VLBI to the _VLBI Imaging Problem_ page of the docs. I can also add it to the paper but I figured the docs are better since more people will probably read those. We follow standard practice here so I cited the standard reference and the specific EHT paper where we define the likelihoods. Let me know if more explanation is needed.

> In a general setting, the user should check the diagnostics of whichever tool they use for optimization/posterior sampling. While this is package-dependent and not part of your code, I think adding some extra steps to the tutorial would make sense to encourage such a workflow. E.g. for AHMC in the black hole image tutorial, the effective sample size and rhat are standard diagnostics.

I added some extra steps to the tutorial showing how the user can compute the effective sample size and split-rhat using the outputs of the HMC sampler. Now for split-rhat I am cheating since they user should really create at least 4 independent chains, but I don't want to get too much into the weeds when it comes to MCMC convergence tools.

> I ran the black hole image example several times and once ran into the following error when calling

Ya that can happen when some of the samples have negative pixels due to round-off and FFT errors. I have changed the call to
```julia
plot(sqrt.(max.(meanimg, 0.0)), title="Mean Image")
```
so that won't happen anymore.

> I wanted to check out the performance claims in the docs (Benchmarks) but I didn't manage to get the code running. The code snippet in the docs fails with
> I also found some recently updated code in examples/benchmark.jl in the GitHub, but I didn't manage to get that running either:

Uggh. Both are now fixed. Those bugs occurred because we recently switched the parameter transformation package so the order of the named tuples matters now when transforming between spaces. This should be fixed in the docs and the examples folder.

> Does the approach used in this paper with this software also merit a mention in the "similar packages" section of the paper?

Yes I added the NIFTy package to the similar software section. However, the package is pretty different since it is only interested in direct imaging using a interesting heirarchical gaussian process prior, and a Gaussian approximation for the posterior. Comrade doesn't have that same type of prior, but it does have a wide variety of different models and access to different posterior approximation methods, since it is interested in different parameterizations.

> I notice that you have automated tests set up but the CI is currently failing and the coverage is currently 0%, although in usually around 75%. Is this a temporary bug with the workflows/uploading

Yes this is a temporary bug that is now fixed. I have been working on some stuff and the main branch version isn't passing tests yet. I think I have most of that fixed right now, but the currently released version was passing tests.

**Comment by cescalara** [comment]
Hi @ptiede, thanks for the fast response! 

> I added a very very brief explanation about the likelihood we use in VLBI to the _VLBI Imaging Problem_ page of the docs. I can also add it to the paper but I figured the docs are better since more people will probably read those. We follow standard practice here so I cited the standard reference and the specific EHT paper where we define the likelihoods. Let me know if more explanation is needed.

I think the new section in the docs is great! Now it is obvious to readers where to look for more information about the code implementation.

> I added some extra steps to the tutorial showing how the user can compute the effective sample size and split-rhat using the outputs of the HMC sampler. Now for split-rhat I am cheating since they user should really create at least 4 independent chains, but I don't want to get too much into the weeds when it comes to MCMC convergence tools.

Sure, I understand. I think what you have added is enough to highlight that one should also think about these things. One small gripe: The ESS is more about autocorrelation and estimation error. I get what you are trying to say with "MCMC estimates converges as $\sqrt{ESS}$", but strictly it is the estimation error that is proportional to $1/\sqrt{ESS}$ (see, e.g. the [Stan manual](https://mc-stan.org/docs/reference-manual/effective-sample-size.html)).

> Uggh. Both are now fixed. Those bugs occurred because we recently switched the parameter transformation package so the order of the named tuples matters now when transforming between spaces. This should be fixed in the docs and the examples folder.

No worries, I ran the updated version without issues and could reproduce your performance claims within some small expected differences due to our different systems.

Finally, a couple more small suggestions:

* In the black hole image example, I like the diagnostic plots at the end, especially the one showing the model in the data space. It could also be cool to show many points from the posterior, or their distribution, instead of just the MAP, if this would be straightforward (like a visual posterior predictive check). I have found similar visualisations to be helpful when working with/debugging these sort of fits. 

* It also wasn't so clear to me how to interpret the residuals plot, is a normalized residual of 3 something like a "3sigma" deviation relative to the data and its error bars in the previous plot? The x-axis seems the same but has a different label (sorry, non-expert on radio here...)

**Comment by ptiede** [comment]
> Sure, I understand. I think what you have added is enough to highlight that one should also think about these things. One small gripe: The ESS is more about autocorrelation and estimation error. I get what you are trying to say with "MCMC estimates converges as ", but strictly it is the estimation error that is proportional to  (see, e.g. the Stan manual).

I had hoped that was what my sentence was conveying, but unfortunately not! It now says "the Monte Carlo standard error shrinks as sqrt(ESS)" hopefully that is clearer.

>In the black hole image example, I like the diagnostic plots at the end, especially the one showing the model in the data space. It could also be cool to show many points from the posterior, or their distribution, instead of just the MAP, if this would be straightforward (like a visual posterior predictive check). I have found similar visualisations to be helpful when working with/debugging these sort of fits.

Sure! I can add some draws from the posterior. They aren't really predictive checks since I am not running them through the data likelihood but it should be helpful nonetheless. 


>It also wasn't so clear to me how to interpret the residuals plot, is a normalized residual of 3 something like a "3sigma" deviation relative to the data and its error bars in the previous plot? The x-axis seems the same but has a different label (sorry, non-expert on radio here...)

No problem! The normalized residuals are given by the difference between the data and the model divided by the error on the data. So a 3 is exactly a three sigma outlier. I added a brief description of the normalized residuals to the

**Comment by cescalara** [comment]
Great, I'm happy with all the changes, so I'll close this issue now.
